apiVersion: apps/v1
kind: Deployment
metadata:
  name: restoran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: restoran
  template:
    metadata:
      labels:
        app: restoran
    spec:
      containers:
      - name: restoran
        image: kadampravin/my-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: restoran-service
spec:
  selector:
    app: restoran
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
